### ISSUE TITLE
Disable animations

### ISSUE THREAD

**Issue by Fuzzyma** [antoniandre/splitpanes#114]
Is there a way to disable the animations of the panes?

**Comment by antoniandre** [comment]
Hi @Fuzzyma, yes this is possible via CSS:

```css
.splitpanes .splitpanes__pane {transition: none;}
```

Hope it helps!

**Comment by vinaysudani** [comment]
I needed to add !important to make it work
```css
.splitpanes .splitpanes__pane {transition: none !important;}
 ```
