### ISSUE TITLE
Customizing dividers, where to put override css?

### ISSUE THREAD

**Issue by mikeerickson** [antoniandre/splitpanes#121]
I am reviewing the code from https://codepen.io/antoniandre/pen/XxRZmB and am trying to something similar in my app (I want the single pixel divider line without the grab tool)

I have tried adding the customized css (see below) everywhere and it never works? 
What am I missing here?
Where should it go?

In my app, I am import as follows

```js
import { Splitpanes, Pane } from 'splitpanes'
import 'splitpanes/dist/splitpanes.css'
```

And I have tried putting the css below in the <script> section of component, in a global `.scss` file

```scss

.splitpanes {
    &__splitter {
        background-color: #ccc;
        position: relative;
    }

    &__splitter:before {
        content: '';
        position: absolute;
        left: 0;
        right: 0;
        top: 0;
        bottom: 0;
        transition: 0.4s;
    }
    &--vertical > &__splitter:before {
        left: -30px;
        right: -30px;
    }
    &--horizontal > &__splitter:before {
        top: -30px;
        bottom: -30px;
    }
}
```
