### ISSUE TITLE
HowTo: Hide the center small lines in the splitpane?

### ISSUE THREAD

**Issue by dfarrNTST** [antoniandre/splitpanes#85]
Is there a way to hide the 2 small lines that appear in the middle of each splitpane?

**Comment by zcqno1** [comment]
Just overwrite the `.splitpanes__splitter` style. The two small lines is exactly declared by `.splitpanes__splitter::before` and `.splitpanes__splitter::after`.

see [#do-your-own-style](https://antoniandre.github.io/splitpanes/example-home-view#increased-touch-zone)

**Comment by antoniandre** [comment]
Thanks @zcqno1.
yes this suffices:

```css
.splitpanes.default-theme .splitpanes__splitter:after, 
.splitpanes.default-theme .splitpanes__splitter:before {display: none;}
```
