### ISSUE TITLE
iframe trouble

### ISSUE THREAD

**Issue by imoldfella** [antoniandre/splitpanes#88]
Nice library! I did run into trouble with iframes. I get that iframes mess up the event bubbling; I don't know if this is possible, but I was wondering if when the mouse when down if it would make sense to capture the entire screen with a transparent div, like a modal does?

**Comment by antoniandre** [comment]
Hi @imoldfella, thanks for your feedback.
I think I know what you are talking about: probably not capturing the event mouseup when dragging and releasing over an iframe.

This is normal as the iframe does not have the same DOM document, but very easy to prevent.
This should be handled outside of splitpanes, and here is how:

The splitpanes container gets a `splitpanes--dragging` while dragging a splitter.

so you can either add a `:before` mask over your iframe or set the iframe to `pointer-events: none` while dragging.

something like: 

```css
.splitpanes--dragging .iframe-wrapper:before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  z-index: 100;
}
```

Hope it helps!
Please reopen the issue if not solved.
